# Generated by Django 5.1.2 on 2024-10-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовка')),
                ('description', models.TextField(verbose_name='Описание')),
                ('completed', models.BooleanField(verbose_name='статус выполнения')),
                ('created', models.DateTimeField(verbose_name='время создания задачи')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Основные задания ',
            },
        ),
    ]
